config/routes.rb
Rails.application.routes.draw do

  resources :comments
  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :projects do
    put :sort, on: :collection
  end

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="collapse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <ul class="list-unstyled">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper('nav-link') %>
      </ul>
    </div>
  </div>
</div>

<div class="masthead clearfix navbar-inverse">
  <div class="inner">
    <h3 class="masthead-brand">Algan Rustinya</h3>
    <nav class="nav nav-masthead">
      <%= nav_helper 'nav-link', '' %>
      <%= login_helper('nav-link') %>
    </nav>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Algan's Blog</h1>
    <p class="lead blog-description">Put your blog out into the world and hope that your talent will speak for itself. 
    </p>
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="collapse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <ul class="list-unstyled">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper('nav-link') %>
      </ul>
    </div>
  </div>
</div>

<div class="blog-masthead clearfix navbar-inverse">
  <div class="container">
    <h3 class="blog-brand">Algan Rustinya</h3>
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper('nav-link') %>
    </nav>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Welcome to my personal blog! My name is Algan and I have a passion for sharing my thoughts and interests. </p>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/alganbr" target="_blank"><%= fa_icon "github" %> GitHub</a></li>
      <li><a href="https://www.linkedin.com/in/algan-rustinya-237582b9" target="_blank"><%= fa_icon "linkedin" %> LinkedIn</a></li>
      <li><a href="https://www.facebook.com/alganrustinya" target="_blank"><%= fa_icon "facebook" %> Facebook</a></li>
      <li><a href="mailto:algan_br@hotmail.com"><%= fa_icon "envelope" %> E-mail</a></li>
    </ol>
  </div>
</div>

app/views/shared/_project_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Projects", projects_path %> / 
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_project_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Algan's Portfolio</h1>
    <p class="lead text-muted">These are a collection of my past works which represent my field of interests and coding style.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
    <p><%= link_to 'Add a New Project', new_project_path if logged_in?(:admin) %></p>
  </div>
</section>

app/views/shared/_project_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h3 class="text-white">Want to see more?</h3>
        <h5 class="text-white">Check out more of my works on:</h5>
        <ol class="list-unstyled social-links">
          <li ><a class="nav-link" href="https://github.com/alganbr" target="_blank"><%= fa_icon "github" %> GitHub</a></li>
          <li><a class="nav-link" href="https://drive.google.com/open?id=0B4MP_OdsGL8GbF9kME1XVXlreUE" target="_blank"><%= fa_icon "file-text" %> Resume</a></li>
        </ol>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'nav-link', 'li' %>
          <%= login_helper('nav-link') %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "Algan Rustinya", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>