config/routes.rb
Rails.application.routes.draw do

  resources :comments
  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :projects do
    put :sort, on: :collection
  end

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body, :main_image, :thumb_image

  mount_uploader :main_image, ProjectUploader
  mount_uploader :thumb_image, ProjectUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, admin: :all
  layout "project"

  # GET /projects
  def index
    @projects = Project.all.order('position ASC')
  end

  # GET /projects/sort
  def sort
    params[:order].each do |key, value|
      Project.find(value[:id]).update(position: value[:position])
    end

    render body: nil
  end

  # GET /projects/1
  def show
    @page_title = @project.title
    @seo_keyword = @project.body
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.position = Project.count
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:title, 
                                      :subtitle, 
                                      :body, 
                                      :main_image, 
                                      :thumb_image, 
                                      :url,
                                      technologies_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :main_image %>
        <%= f.file_field :main_image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :thumb_image %>
        <%= f.file_field :thumb_image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :link %>
        <%= f.text_field :url, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>

      <div>
        <%= link_to_add_association 'Add Technology', f, :technologies %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Project Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="col-xl-4 col-lg-6 col-md-6">
  <div class="card" data-id="<%= project.id %>">
    <%= link_to image_tag(project.thumb_image), project_path(project) %>
    <h4 class="card-title"><%= link_to project.title, project_path(project) %></h4>
    <p class="card-text">
      <%= project.subtitle %>
    </p>
  </div>
</div>

app/views/projects/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/projects/edit.html.erb
<div class="container project-container">
  <h1>Edit Project</h1>

  <%= render 'form', project: @project %>

  <%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<%= render 'shared/project_masthead' %>
<div class="album text-muted">
  <div class="container">
    <div class="row <%= 'sortable' if logged_in?(:admin) %>">
      <%= render partial: 'project', collection: @projects %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container project-container">
  <h1>Create a new Project Item</h1>

  <%= render 'form', project: @project %> 

  <%= link_to 'Back', projects_path %> 
</div>

app/views/projects/show.html.erb
<div class="container project-container">
  <div class="row">
    <div class="col-md-7 text-center">
      <%= image_tag @project.main_image %>
      <% if @project.url and not @project.url.empty? %>
        <%= link_to 'Visit', @project.url, target: "_blank", class: 'btn btn-lg btn-info visit-button' %>
      <% end %>
    </div>

    <div class="col-md-5">
      <h1><%= @project.title %></h1>

      <hr>

      <em><%= @project.subtitle %></em>

      <p><%= @project.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <p>
      <%= @project.technologies.map{|p| p.name}.join(", ") %>.
      </p>

      <%= link_to 'Edit |', edit_project_path(@project) if logged_in?(:admin) %>
      <%= link_to 'Back', projects_path %>
      
    </div>
  </div>
</div>